name: Package release

on:
  release:
    types: [created]

jobs:
  deploy_osx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          #- name: Run tests
          #timeout-minutes: 30
          #run: .github/workflows/scripts/run_tests_python.sh
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: .github/workflows/scripts/release_osx.sh
